### ISSUE TITLE
Izbiranje igralcev in struktura baze

### ISSUE THREAD

**Issue by jaanos** [VavdiG14/Ultimate-Fantasy-Premier-League#3]
Poskusil sem se registrirati in izbrati ekipo, a mi sprva ni uspelo sestaviti celotne. Mislim, da je problem tukaj:

https://github.com/VavdiG14/Ultimate-Fantasy-Premier-League/blob/d4144c84fb784e658d897da63ae7088b5bd0fc6a/views/izberiEkipo.html#L204

Če prav razumem, torej preprečita dodajanje igralca, če je igralcev na določeni poziciji že preveč, ne glede na pozicijo igralca, ki ga želita dodati. Bolje bo, če preverita, ali je na poziciji igralca, ki ga želita dodati, še kaj prostora, in preprečita dodajanje, če ga ni. Seveda bi bilo lepo tudi uporabnika opozoriti, kakšne so omejitve.

Sem potem le uspel sestaviti ekipo 15 igralcev, a ko kliknem *Naprej* (lepo bi bilo, če bi se kurzor miške spremenil ob prehodu čez gumb - nastavita ustrezen CSS), dobim napako. Verjetno želita tudi preprečiti klik na *Naprej*, če ekipa ni popolna.

Še to: opažam, da ekipo hranita v bazi kar kot seznam ID-jev v nizu. To seveda ni zaželeno - namesto tega naredita novo tabelo s tujima ključema na uporabnika in igralca - glavni ključ sta potem kar oba stolpca skupaj (na ER diagramu bo seveda tej tabeli ustrezala relacija med uporabnikom in igralcem). Tako bo mogoče npr. seznam igralcev v ekipi dobiti z eno samo poizvedbo. Podobno naj velja tudi za uporabnikove točke v prejšnjih krogih (to bo šibka entiteta, saj je odvisna od uporabnika in kroga, ki je samo številka in sam zase ni entiteta).

Poskrbita tudi za glavne ključe v ostalih tabelah - pri uporabnikih bi bilo bolje, če bi za glavni ključ imela številski ID z lastnostjo `AUTOINCREMENT` (`uporabnisko_ime` ima potem lahko lastnost `UNIQUE`); tak glavni ključ dodajta tudi k tabelama `Dogodki` in `Tocke`. Pri prejšnji ne potrebujeta informacije o krogu, saj tega določa že tekma; pri slednji pa lahko morda krog nadomestita z referenco na tekmo.

**Comment by VavdiG14** [comment]
Tako, popravila sva vse kar ste napisali zgoraj.

**Comment by jaanos** [comment]
V redu, sedaj deluje, tako da se lahko z @alenFMF domenita za termin zagovora.

Lahko se sicer še malo poigrata s kakšnimi lepotnimi popravki - npr. sedaj se seznama vseh in izbranih igralcev nekoliko prekrivata; kot rečeno, lahko poskrbita še za ustrezen kurzor za gumbe (v CSS lahko za želeni element nastavita `cursor: pointer`).
